spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/oAuth
    username: postgres
    password: postgres
    hikari.schema: public

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github:
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
          vk:
            provider: vk
            client-id: ${VK_CLIENT_ID:vk-client-id}
            client-secret: ${VK_CLIENT_SECRET:vk-client-secret}
            redirect-uri: ${VK_REDIRECT_URI:vk-redirect-uri}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: email, wall
          yandex:
            provider: yandex
            client-id: ${YANDEX_CLIENT_ID:yandex-client-id}
            client-secret: ${YANDEX_CLIENT_SECRET:yandex-client-secret}
            redirect-uri: ${YANDEX_REDIRECT_URI:yandex-redirect-uri}
            authorization-grant-type: authorization_code
            scope: login:birthday, login:email, login:info, login:avatar
        provider:
          vk:
            #revoke=1 needs to always show vk dialog
            authorization-uri: https://oauth.vk.com/authorize?revoke=1
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=5.133&fields=photo_max
            user-name-attribute: email
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: default_email
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
